name: Build LLVM Obfuscator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.4

    steps:
    # Step 1: Checkout the repository (your fork)
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          ref: main

    # Step 2: Install dependencies (CMake, GCC, Clang, etc.)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git ninja-build

    - name: Configure CMake
      run: |
        wget https://heroims.github.io/obfuscator/NewPass/ollvm14.patch
        git clone -b release/14.x --depth=1 https://github.com/llvm/llvm-project.git
        cd llvm-project
        git apply --reject --ignore-whitespace ../ollvm14.patch

        cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" -DCMAKE_BUILD_TYPE=Release
        cd build; ninja clang


    # Step 5: Verify the build (optional)
    - name: Verify build
      working-directory: build
      run: |
        ./bin/clang --version

    # Step 6: Upload build artifacts using the latest action version
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: obfuscator-build
        path: build/bin/
